### ISSUE TITLE
API - Hooks: Add 'useReducer' API

### ISSUE THREAD

**Issue by bryphe** [bryphe/reason-reactify#21]
We currently don't have a `useReducer` API equivalent, as documented [here](https://reactjs.org/docs/hooks-reference.html#usereducer)

This is an important API to have, as it is a great fit for Reason. (It'll be tremendously useful for building out widgets in [Revery](https://github.com/bryphe/revery) - managing 'internal' state for things like lists, sliders, combo-boxes, etc).

This issues encompasses:
- Adding the API to [Reactify.re](https://github.com/bryphe/reason-reactify/blob/master/lib/Reactify.re), so that the return module from the functor has this capability. See `useState` and `useContext` for examples.
- Adding test cases. See the [`HooksUseStateTest`](https://github.com/bryphe/reason-reactify/blob/master/test/HooksUseStateTest.re) for examples.
- Adding an example that uses hooks

**Comment by jchavarri** [comment]
Started working on this in https://github.com/bryphe/reason-reactify/pull/34 😄
